language: php

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: SYMFONY_VERSION="^4.4"
    - php: 7.4
      env: SYMFONY_VERSION="^4.4"
    - php: 7.4
      env: SYMFONY_VERSION="^5.0"
    - php: 7.4
      env: SYMFONY_VERSION="^5.1"

install:
  - composer create-project "symfony/skeleton:${SYMFONY_VERSION}" flex
  - cd flex
  - composer config extra.symfony.allow-contrib true
  - composer require mael/recaptcha-bundle --prefer-dist --no-progress --no-suggest