services:
  Mael\InterventionImageBundle\MaelInterventionImageManager:
    class: Mael\InterventionImageBundle\MaelInterventionImageManager
    autoconfigure: true
    autowire: true
    arguments:
      $driver: '%mael_intervention_image.driver%'